EXP_NAME: debug
NUM_CLASSES: 2
INPUT:
  EARLY_FUSION: False
MODEL: 
  BACKBONE: resnet18 # resnet18 # ViT3D # PDNet
  MODALITY: 2D
  PRETRAINED_RESNET: False
TRAIN:
  LEARNING_RATE: 0.00005 # 3D: 0.0001 
  NUM_EPOCH: 500
  EARLY_STOP: 1000
  SAVE_PRED_EVERY: 100
  BATCH_SIZE: 512 # 32
TEST:
  BATCH_SIZE: 100
  